version: "3.5"

services:
  app:
    image: busybox
    command: top
    networks:
      mesh:
        ipv4_address: 192.168.16.30
    restart: on-failure
networks:
  mesh:
    ipam:
      driver: default
      config:
      # use static IPs to simplify setup workflow
      - subnet: "192.168.16.0/24"