version: "3.5"

services:
  # deploy service into mesh
  reviews-v3:
    image: berinle/examples-bookinfo-reviews-v3:latest
    ports:
      - "19083:19081" #expose the envoy port to host
      - "9083:9080" #expose the envoy port to host
    networks:
      mesh:
        ipv4_address: 192.168.16.8
    environment:
      - RATINGS_HOSTNAME=127.0.0.1
      - RATINGS_PORT=39082
      - ENABLE_RATINGS=true
    restart: on-failure

  # deploy sidecar along side with service
  reviews-v3-sidecar:
    image: ${KUMA_DP_DOCKER_IMAGE:-kong-docker-kuma-docker.bintray.io/kuma-dp:latest}
    command:
      - run
      - --log-level=info
    volumes:
      - ${KUMA_TOKENS_DIR:-./secrets}/dp-reviews-3:/var/kuma.io/kuma-dp/dp-reviews-3/token
    environment:
      - KUMA_CONTROL_PLANE_API_SERVER_URL=${KUMA_CONTROL_PLANE_API_SERVER_URL:-http://localhost:5681}      
      - KUMA_DATAPLANE_MESH=default
      - KUMA_DATAPLANE_NAME=dp-reviews-3
      - KUMA_DATAPLANE_ADMIN_PORT=9901
      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/var/kuma.io/kuma-dp/dp-reviews-3/token
    network_mode: service:reviews-v3
    depends_on:
      - reviews-v3
    restart: on-failure

networks:
  mesh: {}