version: "3.5"

services:
  # deploy service into mesh
  productpage:
    image: berinle/examples-bookinfo-productpage-v1:latest
    ports:
      - "49081:49081" #expose the envoy port to host
      - "9080:9080"
    networks:
      mesh:
        ipv4_address: 192.168.16.5
    environment:
      - DETAILS_HOSTNAME=127.0.0.1
      - RATINGS_HOSTNAME=127.0.0.1
      - REVIEWS_HOSTNAME=127.0.0.1
      - DETAILS_PORT=29082
      - RATINGS_PORT=39082
      - REVIEWS_PORT=19082
    restart: on-failure

  # deploy sidecar along side with service
  productpage-sidecar:
    image: ${KUMA_DP_DOCKER_IMAGE:-kong-docker-kuma-docker.bintray.io/kuma-dp:latest}
    command:
      - run
      - --log-level=info
    volumes:
      - ${KUMA_TOKENS_DIR:-./secrets}/dp-productpage-1:/var/kuma.io/kuma-dp/dp-productpage-1/token
    environment:
      - KUMA_CONTROL_PLANE_API_SERVER_URL=${KUMA_CONTROL_PLANE_API_SERVER_URL:-http://localhost:5681}
      - KUMA_DATAPLANE_MESH=default
      - KUMA_DATAPLANE_NAME=dp-productpage-1
      - KUMA_DATAPLANE_ADMIN_PORT=9901
      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/var/kuma.io/kuma-dp/dp-productpage-1/token
    network_mode: service:productpage
    depends_on:
      - productpage
    restart: on-failure

networks:
  mesh: {}