version: "3.5"

services:
  # deploy service into mesh
  mongo:
    image: berinle/examples-bookinfo-mongodb:latest
    ports:
      - "37017:37017" #expose the envoy port to host
      - "27017:27017"
    networks:
      mesh:
        ipv4_address: 192.168.16.7
    restart: on-failure

  # deploy sidecar along side with service
  mongo-sidecar:
    image: ${KUMA_DP_DOCKER_IMAGE:-kong-docker-kuma-docker.bintray.io/kuma-dp:latest}
    command:
      - run
      - --log-level=info
    volumes:
      - ${KUMA_TOKENS_DIR:-./secrets}/dp-mongo-1:/var/kuma.io/kuma-dp/dp-mongo-1/token
    environment:
      - KUMA_CONTROL_PLANE_API_SERVER_URL=${KUMA_CONTROL_PLANE_API_SERVER_URL:-http://localhost:5681}      
      - KUMA_DATAPLANE_MESH=default
      - KUMA_DATAPLANE_NAME=dp-mongo-1
      - KUMA_DATAPLANE_ADMIN_PORT=9901
      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/var/kuma.io/kuma-dp/dp-mongo-1/token
    network_mode: service:mongo
    depends_on:
      - mongo
    restart: on-failure

networks:
  mesh: {}