version: "3.5"

services:
  # deploy service into mesh
  details:
    image: berinle/examples-bookinfo-details-v1:latest
    ports:
      - "29081:29081" #expose the envoy port to host
    networks:
      - mesh
    restart: on-failure

  # deploy sidecar along side with service
  details-sidecar:
    image: ${KUMA_DP_DOCKER_IMAGE:-kong-docker-kuma-docker.bintray.io/kuma-dp:latest}
    command:
      - run
      - --log-level=info
    volumes:
      - ../secrets/dp-details-1:/var/kuma.io/kuma-dp/dp-details-1/token
    environment:
      - KUMA_CONTROL_PLANE_API_SERVER_URL={KUMA_CONTROL_PLANE_API_SERVER_URL:-http://localhost:5681}      
      - KUMA_DATAPLANE_MESH=default
      - KUMA_DATAPLANE_NAME=dp-details-1
      - KUMA_DATAPLANE_ADMIN_PORT=9901
      - KUMA_DATAPLANE_RUNTIME_TOKEN_PATH=/var/kuma.io/kuma-dp/dp-details-1/token
    network_mode: service:details
    depends_on:
      - details
    restart: on-failure

networks:
  mesh: {}